import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  AppBar,
  Toolbar,
  Typography,
  Container,
  CssBaseline,
  Drawer,
  List,
  ListItem,
  ListItemText,
  Box,
} from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CssBaseline />
        <AppBar position="static">
          <Toolbar>
            <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
              Next.js Host App
            </Typography>
          </Toolbar>
        </AppBar>
        <Box sx={{ display: "flex" }}>
          <Drawer
            variant="permanent"
            sx={{
              width: 200,
              flexShrink: 0,
              [`& .MuiDrawer-paper`]: { width: 200, boxSizing: "border-box" },
            }}
          >
            <Toolbar />
            <Box sx={{ overflow: "auto" }}>
              <List>
                <ListItem button component="a" href="/">
                  <ListItemText primary="Home" />
                </ListItem>
                <ListItem button component="a" href="/user">
                  <ListItemText primary="Users" />
                </ListItem>
                <ListItem button component="a" href="/logsync">
                  <ListItemText primary="LogSync" />
                </ListItem>
                <ListItem button component="a" href="/logsync-remote">
                  <ListItemText primary="LogSyncRemote" />
                </ListItem>
                {/* Add more sidebar links here */}
              </List>
            </Box>
          </Drawer>
          <Box component="main" sx={{ flexGrow: 1, p: 3 }}>
            <Toolbar />
            {children}
          </Box>
        </Box>
      </body>
    </html>
  );
}
